### PR TITLE
better reason for Y074

### PR DESCRIPTION
**Pull request by ddrabik**
change for issue #316

### CODE REVIEW

**Comment by tomahim** [comment]
About this, I don't understand why it's a good practice to use elements AND attributes directives.

I only use attributes, mainly for compatibility between Angular 1.2 and IE 8 and also because I think it's better not to mix custom elements and attributes for a coherent code.

**Comment by dietergeerts** [comment]
@tomahim, so all of your directives work with all possible tags and they always alter them in some way? Sometimes you just need a whole other kind of tag, and then you use an element directive.

**Comment by tomahim** [comment]
@dietergeerts yeah I see what you mean. No problem with attributes as I'm using my own directive, but I agree it's not perfect if other people should use it. 
Still have no choice for IE issue :)

**Comment by johnpapa** [comment]
i dont think they are easier to identify. i think they are more useful. elements represent an element that may be used and attributes are ideal when a directive enhances an existing element.

**Comment by wardbell** [comment]
I'm not sure why a directive should serve both in element and attribute position. If the directive acts like a web component (e.g, as a semantic tag or a substitute for an HTML element), I'd mark it for use exclusively as an element and it would likely have isolate scope. If it modifies behavior, I'd make it an attribute directive and would be unlikely to give it isolate scope

 I haven't found the need for a class or a comment directive. I could see writing a class directive if it served a styling purpose and seemed more natural to apply as one would a CSS class.

The comment directive was useful *before* they added [`-start` and `-end` to `ngRepeat`](https://docs.angularjs.org/api/ng/directive/ngRepeat#special-repeat-start-and-end-points). These features enable HTML scenarios that could only be implemented with the comment directive previously.

This is how I roll.

**Pull request closed without merging**
