### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by IvanCoronado**
'movieService' isn't being injected in 'moviesPrepService'.

### CODE REVIEW

**Comment by gkalpak** [comment]
The fact that the `moviesPrepService` is not minification-safe is explained [a few lines further down][1]:

> Note: The code example's dependency on `movieService` is not minification safe on its own. For details on how to make this code minification safe, see the sections on [dependency injection](#manual-annotating-for-dependency-injection) and on [minification and annotation](#minification-and-annotation).

[1]: https://github.com/johnpapa/angular-styleguide/pull/630/files#diff-04c6e90faac2675aa89e2176d2eec7d8R1492

**Comment by johnpapa** [comment]
ty

**Comment by zachlysobey** [comment]
uhhh... doesn't @gkalpak's comment above mean that this is not a good merge?

**Comment by johnpapa** [comment]
doh, good point. not enough sleep here.

**Comment by johnpapa** [comment]
reverted

**Pull request merged**
