### PR TITLE
indicate ngInject, encapsulate full controller name

### PR DESCRIPTION
**Pull request by EskoCruz**
[Style Y251](https://github.com/johnpapa/angular-styleguide#style-y251) indicate ngInject, encapsulate full controller name for VS Snippet

### CODE REVIEW

**Comment by EskoCruz** [comment]
This is my first PR for a project this large. I had great incuragement from @MAustinMMDP. Please be kind. :)

**Comment by MAustinMMDP** [comment]
Thankyou for this @EskoCruz - it was next on my TODO list.

**Comment by johnpapa** [comment]
thanks for the PR.

why are you suggesting renaming the placeholder with a `name` suffix? i'd like to understand

**Comment by MAustinMMDP** [comment]
@johnpapa - Not sure why @EskoCruz chose the name suffix but I chose it for the other templates/snippets to demonstrate the need to camelcase, however, in regards to the controller, I would suggest the name part be a placeholder so it can be prefixed automagically to "Controller". I would also make sure the placeholders match the approved WebStorm live templates, e.g., dependency1 to dependency. Lastly, the directive should not be capitalized; I would use directiveName.

**Comment by johnpapa** [comment]
im cool with that.

**Comment by EskoCruz** [comment]
@MAustinMMDP - Thank you I will keep going.
@johnpapa - I was trying to stay constant with the WebStorm templates #544 
I am more than happy to go with whatever you wish to abide by with these templates.

**Comment by johnpapa** [comment]
I dont feel strongly either way about Name or no name. I do care that we have a reason that's all :) Feel free to make a pitch for either.

**Comment by johnpapa** [comment]
Any final changes to this? or do you want more folks to test it?

**Comment by EskoCruz** [comment]
I would say Ready for testing for Visual Studio Javascript plugin. working on Typescript next.

**Comment by johnpapa** [comment]
closing as we never got full testing on it.

feel free to open a new PR if we get more testers.

**Pull request closed without merging**
