### PR TITLE
added [] into all .module lines to prevent $injector error

### PR DESCRIPTION
**Pull request by leongaban**
Fixed all modules, example:

`.module('myFactory', [])` 

`.module('myController', [])` 

etc

### CODE REVIEW

**Comment by johnpapa** [comment]
cant do it to all files as that would create the module in every file.

it should only be done in module files

**Comment by leongaban** [comment]
`[]` removed from the ngfilter now

**Comment by johnpapa** [comment]
cant do it to all files as that would create the module in every file.

it should only be done in module files

**Comment by johnpapa** [comment]
closing. if you want to resubmit for module files, please do

**Pull request closed without merging**
