### PR TITLE
Fix moviesPrepService typo in Resolve section

### PR DESCRIPTION
**Pull request by jeffsheets**
Fix moviesPrepService typo in Route Resolve section. It was previously just moviePrepService but this did not match how it was called in the resolve block.

### CODE REVIEW

**Comment by reflexdemon** [comment]
:+1: Good find.

**Comment by johnpapa** [comment]
Good catch ... but there are a few more too. Care to make all the changes and I will merge?

**Comment by jeffsheets** [comment]
The other ones appear to be correct code to me, but maybe I'm overlooking something. Is there a specific line that you are referring to? Let me know and I'll touch it up

**Comment by johnpapa** [comment]
just consistency. i figured they should all be the same

**Comment by jeffsheets** [comment]
ah ok. will do. i'll send it shortly

**Comment by johnpapa** [comment]
thanks

**Pull request merged**
