### PR TITLE
Slush Angular Generator

### PR DESCRIPTION
**Pull request by reflexdemon**
This is a PR which is for adding notes for slush based angular generator that is built with this style guide.

### CODE REVIEW

**Comment by johnpapa** [comment]
I need some help reviewing this one before I can recommend it. Any takers?

**Comment by voor** [comment]
The webpage documentation seems to be out of sync with the actual generator.  Some of the things like the filter generator documentation do not conform to the style guide, but the actual generator itself does.  Maybe have the documentation auto-generated?  Looks like it's static at the moment.

**Comment by reflexdemon** [comment]
@voor thanks for this input. It was manually built and that could be the reason. As soon as I find time I will get it fixed and let you know.

**Comment by reflexdemon** [comment]
@voor Just updated the documentation and corrected some links etc. If you find time please provide your feedback to us.

**Comment by voor** [comment]
Link to github project (keep looking for it in the commit files): [angular-gulp slush generator](http://reflexdemon.github.io/slush-angular-gulp/)

**Comment by reflexdemon** [comment]
@johnpapa Do you think this can be merged?

**Comment by voor** [comment]
I haven't really had a chance to look over it, but what I did review looked like a lot of hard work went into this.  I'm about to start up another Angular project, and I plan on giving this more of  trial run in the coming weeks.

**Comment by johnpapa** [comment]
i have not tried this, but i read through it.

Also please see generator-hottowel as an idea of what I built with a dead simple app generator (no sub generators).

i like a lot of this, but not a fan of the subfolders by type everywhere. i prefer not to have those until i need them. so by default i would not enjoy a generator that does that. I'd recommend removing that.

The components folder is one I would remove too. heat and todo should just be under app, IMO.

I do want a generator that follows this guide, so if you can get everything to follow it, I'd be game

**Comment by reflexdemon** [comment]
:smile: will do and get back.

**Comment by johnpapa** [comment]
it is your generator ... so i totally understand if you dont want to , either. so no worries

**Comment by voor** [comment]
What do you mean by no sub-generators?  As in, not having a way to generate a new controller without copy/pasta?  Because that was one of the more appealing things about this generator -- that I could slap it on an existing project and fly from there.

**Comment by reflexdemon** [comment]
I am not going to remove sub generators but would take the suggestion on placing the demos outside of component folder.

**Comment by johnpapa** [comment]
I said that hottowel has no sub generators. It is simply a starter project. I'd be happy to have someone create the PR to have them added though.

Slush has them.


To be honest, I never use sub generators. I use snippets. But I do know people like them

**Comment by johnpapa** [comment]
I was not suggesting you remove sub generators. I just said hottowel doesnt have them.

**Comment by voor** [comment]
Apologies, think I'm adding more confusion to this thread than removing it. :sob:

**Comment by johnpapa** [comment]
If you want to keep the components and the folders by type, then I can't accept this PR as that is not the structure this guide follows. If you want to make it follow this guide, I'll reconsider reviewing and merging.

Sorry

**Comment by reflexdemon** [comment]
@johnpapa This is the new dir structure. I just wanted to run by you before I push the changes.

```
.
├── bower.json
├── gulpfile.js
├── karma.conf.js
├── package.json
├── README.md
└── src
    └── app
        ├── app.js
        ├── app.less
        ├── assets
        │   └── slush-angular-gulp.png
        ├── heat
        │   ├── aheat.js
        │   ├── heat-controller.js
        │   ├── heat-route.js
        │   ├── service
        │   │   └── heat_service.js
        │   └── view
        │       └── heat.html
        ├── index.html
        ├── styles
        │   └── _base.less
        └── todo
            ├── todo.html
            ├── todo.js
            ├── todo.less
            ├── todo-controller.js
            ├── todo-controller.spec.js
            └── todo-route.js

```

**Pull request closed without merging**
