### PR TITLE
Webstorm live template to create a component

### PR DESCRIPTION
**Pull request by jacobwarduk**

### CODE REVIEW

**Comment by johnpapa** [comment]
Thanks for the contributions. Can you help get some folks to review this?

I dont use WebStorm, so before we merge it I want to make sure it's up to date.

Perhaps some of the folks from webstorm team , even

**Comment by prigara** [comment]
Hi @jacobwarduk! Thanks for you PR. I've noticed that it's missing a comma in the line with `templateUrl`.

**Comment by jacobwarduk** [comment]
Thanks for pointing this out @prigara, it has been fixed.

**Comment by jacobwarduk** [comment]
@prigara as part of the WebStorm team, could you give this a quick review to see if we can get it merged into the repo please?

Kind regards, Jacob.

**Comment by prigara** [comment]
@jacobwarduk hey, Jacob! Tried it in WebStorm 2017.3, works fine for me!
@johnpapa can you please merge it? Thank you!

**Comment by johnpapa** [comment]
done

and thank you all!

**Pull request merged**
