### PR TITLE
Brackets typo and punctuation correction

### PR DESCRIPTION
**Pull request by MAustinMMDP**
Newbie here. I had thought I was creating a new PR for commits [92a05b3](https://github.com/MAustinMMDP/angular-styleguide/commit/92a05b377a00ce1dcc481b51962ef15aad576a57) and [f803ca8](https://github.com/MAustinMMDP/angular-styleguide/commit/f803ca88a3d5a9bea09d4637cc0aec46d38f7fd0) but it appears all of my commits including the ones in PR #532 came with. I apologize for any confusion. To clarify, the two commits referenced above are related to Brackets Style Y254 and the remaining commits are for WebStorm Style Y252 also found in PR #532.

### CODE REVIEW

**Comment by MAustinMMDP** [comment]
Newbie alert! It appears that this PR includes commits found in my other PR, #532. I will go ahead and close #532 to avoid confusion. the above comment is in reference to

**Comment by johnpapa** [comment]
Thanks.

Can we get some community folks to test this out?

**Comment by johnpapa** [comment]
ok, so should #529 be closed?

**Comment by MAustinMMDP** [comment]
Yes, #529 can be closed.

**Comment by joshtoo** [comment]
@johnpapa - I'll load this up on my other DevBook Pro and give it a side by side run against the currently released versions for Webstorm and Brackets. ~30 minutes, need some Java so I can think straight.

**Comment by joshtoo** [comment]
WebStorm - Controller

screen shot 2015-09-26 at 8 26 33 am

**Comment by johnpapa** [comment]
We dont need valid:this when the Controller name is UpperCamelCase.

**Comment by joshtoo** [comment]
Should have finished my coffee first :)

**Comment by joshtoo** [comment]
WebStorm - Factory

screen shot 2015-09-26 at 8 41 26 am

Outside of the nitpicky "code" thing this and the Controller are much cleaner our of the box.

**Comment by johnpapa** [comment]
I think you leave the function empty. k @MAustinMMDP ?

**Comment by joshtoo** [comment]
WebStorm - Module

screen shot 2015-09-26 at 8 51 28 am

Addition of the closure brings the snippet inline with Style Y010

**Comment by joshtoo** [comment]
WebStorm - Directive

screen shot 2015-09-26 at 9 06 53 am

**Comment by joshtoo** [comment]
WebStorm - Service

Has the same "code" change required, I'll spare you the image spam

**Comment by joshtoo** [comment]
WebStorm - Filter

Fine the way it is imo

**Comment by joshtoo** [comment]
WebStorm - Partials

Remove "code" from the ngconfig & ngrun partials. Outside of that they are clean and inline with the styles defined in the guild.

@MAustinMMDP - Outside of the nitpicky little things above this is a big improvement over what exists and I'll be putting it to good use this afternoon. Thanks :)

**Comment by MAustinMMDP** [comment]
Thanks for checking it @joshtoo! Agreed @johnpapa I will remove the "code" thing.

**Comment by joshtoo** [comment]
@johnpapa - Once you decide on what you want here, i'll open another issue and port @MAustinMMDP's changes over to sublime

**Comment by johnpapa** [comment]
Having the word `code` appear means you have to delete. If the live template can just leave a placeholder for the cursor there, that's more natural. Otherwise, remove it.

**Comment by MAustinMMDP** [comment]
Yes, I agree and have left the variables in place and only removed the default values. Should work perfectly now.

**Comment by joshtoo** [comment]
@MAustinMMDP - Flows really well now across the board +1

**Comment by joshtoo** [comment]
@johnpapa - Went through the issues list and referenced those that this PR satisfies imo.

**Comment by joshtoo** [comment]
@MAustinMMDP - Went through all of the brackets snippets. The only thing I would change would be the comments in ngdirective as they are not inline with Y220

**Comment by MAustinMMDP** [comment]
I did not look closely at the brackets templates; I just noticed a couple errors while referencing them for the WebStorm live templates. I did not care for the comments either so I will remove them from WebStorm ngdirective after breakfast :). I am familiar with .yaml and planned on going through the brackets snippets next week unless this is already being worked on? 

There are also some brackets snippets in the download that are not referenced in the styleguide. I am sure there is a use case but I would like some input before creating live templates before porting them to WebStorm.

**Comment by MAustinMMDP** [comment]
@johnpapa - I have made all the changes so they should be good to go

**Pull request merged**
