### PR TITLE
style-y038 : clarify when to use the controllerAs syntax

### PR DESCRIPTION
**Pull request by drKnoxy**
Also i think the third bullet point helps cover the fact that you *can* use multiple names
https://github.com/johnpapa/angular-styleguide/issues/577
https://github.com/johnpapa/angular-styleguide/issues/462

### CODE REVIEW

**Comment by drKnoxy** [comment]
We may also want to update for `controller: 'MyController as vm'` syntax
https://github.com/johnpapa/angular-styleguide/issues/582

**Comment by mikeerickson** [comment]
I think it shield be used all the time.  But that's just my opinion :)

**Comment by MAustinMMDP** [comment]
The word "relavent" should be spelled "relevant"

**Comment by johnpapa** [comment]
not sure i agree.

**Pull request closed without merging**
