### PR TITLE
WebStorm, Sublime Text, Brackets and vim templates and snippets update

### PR DESCRIPTION
**Pull request by MAustinMMDP**
I went ahead and created/updated the Sublime Text and Brackets snippets to match the WebStorm live templates. The README is also updated in Commit [8e12877](https://github.com/johnpapa/angular-styleguide/commit/8e1287757da5cecc14d79ccf275507ec96f72e1a).

### CODE REVIEW

**Comment by johnpapa** [comment]
has merge issue.

thanks for doing these. ive asked some folks on twitter to help test them

**Comment by MAustinMMDP** [comment]
Lovely merge issue that :). Will attempt a fix after dinner.

**Comment by MAustinMMDP** [comment]
It appears to be fixed. The conflict was with the README.

**Comment by belchugov** [comment]
@MAustinMMDP It would be useful to add file templates for Webstorm, should be the same structure as the ones for the snippets.

**Comment by johnpapa** [comment]
@belchugov  Im open to PRs on snippets and templates. Feel free to contribute any or all :)

**Comment by MAustinMMDP** [comment]
Great idea @belchugov! It will only take a few minutes so I will push them over this morning after breakfast.

**Comment by MAustinMMDP** [comment]
Added WebStorm file templates and updated the README.

**Comment by belchugov** [comment]
And one nerdy note, I saw that it's inconsistent IIFE: `(function() {` or `(function () {`, I guess based on the style guide that first option should be the right one, but as it's anonymous function there should be space after the declaration. @johnpapa what's you take on that?

**Comment by MAustinMMDP** [comment]
Confused, I have never heard of an instance where you would place a space before the operator? 

I personally questioned the placement of the last operator but either way works:

(function() {  /* code */  }()); // Crockford recommends this one
(function() {  /* code */  })(); // This styleguide

**Comment by zachlysobey** [comment]
@belchugov @MAustinMMDP:
@johnpapa approved [this commit](https://github.com/johnpapa/angular-styleguide/commit/92c7a8d5828aa991b8c3caaaa57d35fee53b671e), from [this issue](https://github.com/johnpapa/angular-styleguide/pull/496) so it appears he's on the side of `(function() {`  (as am I).

**Comment by MAustinMMDP** [comment]
@belchugov, @johnpapa - The extra line breaks have been removed and the IIFE is in sync with the styleguide and other snippets/templates already merged.

**Comment by MAustinMMDP** [comment]
Ok, after more research, I think we should have a discussion on Style [Y010](https://github.com/johnpapa/angular-styleguide#style-y010) which advocates an IIFE format of ```(function() { / code */ })();```. I was looking at the wrong source for my information when I responded to @belchugov earlier. The Crockford [version](http://javascript.crockford.com/code.html#function) is ```(function () { /* code / }());```. 

Your thoughts @johnpapa?

**Comment by MAustinMMDP** [comment]
@johnpapa has [spoken](https://github.com/johnpapa/angular-styleguide/issues/550) and all the templates IIFE's are constructed to his liking :)

**Comment by johnpapa** [comment]
We'll need a few more people to look over these before merging.

**Comment by MAustinMMDP** [comment]
Agreed. The file templates are a little different than the other formats so they need to be thoroughly tested.

FYI: I will be working on the remaining snippets, i.e., VIM, VS, today to match the others. I have not worked with VIM before but the code looks familiar to me and I have Visual Studio (I just prefer WebStorm) on my desktop.

**Comment by rupamroy** [comment]
@MAustinMMDP I was testing the webstorm templates , I would suggest the names to be shorter. 
like angular.app-template.js instead of angular.app.webstorm-file-template.js .
We already know they are file generation templates for angular so I believe we can skip that part.

It would be great if the templates could be grouped but looks like Webstorm does not support that now 
https://youtrack.jetbrains.com/issue/IDEA-139888

**Comment by MAustinMMDP** [comment]
Thanks for testing @rupamroy. I agree, and will shorten it in the morning. 

Yeah, unfortunately it does not appear to be an option right now. I tried to create a directory for the templates but WebStorm did not see it.

**Comment by johnpapa** [comment]
we need to fix the merge conflicts here and see if there are any more reviewers for it

**Comment by MAustinMMDP** [comment]
I will fix the merge conflicts in the morning.

**Comment by MAustinMMDP** [comment]
@johnpapa - Merge conflicts fixed now we just need more reviewers.

**Comment by EskoCruz** [comment]
@MAustinMMDP I am more than happy to help. Maybe it should be should be more evident of what you need me to do by saying the word "reviewer", as in just checking to see if the live templates work. I am fine with being talked to like a child so as long I know I am helping you in the correct fashion.

**Comment by MAustinMMDP** [comment]
Thanks @EskoCruz! We just need someone to test out the snippets/templates for WebStorm, Sublime, Brackets and vim to make sure they work correctly. A glance over the code would be great too just to make sure it is in sync with this styleguide.

**Comment by zachlysobey** [comment]
Any reason *not* to have `var vm = this` in the controller for the directive snippet?

*note:* I've only checked out the sublime snippets (so far)

**Comment by zachlysobey** [comment]
@MAustinMMDP  in #602 you said that was covered in this PR, but It looks like your sublime snippets are all using spaces still...

**Comment by MAustinMMDP** [comment]
Sorry @zachlysobey They should be fixed now. I typically work in WebStorm and had only checked to see that the Tab Width matched yours and had forgotten that I also needed to convert the indentation to tabs. 

FYI: If anyone wants to convert the tabs to spaces they just need to go to Preferences >  Settings - User and add "translate_tabs_to_spaces" and set it to true.

**Comment by MAustinMMDP** [comment]
@zachlysobey I did not include the `var vm = this` because it was not in the original snippet. There is no reason why we should not include it because it is shown in Style Y075, however, IMO it is not essential as it was only used as an example of injecting $scope.

**Comment by zachlysobey** [comment]
@MAustinMMDP Thanks for the quick responses!

In trying these (Sublime) snippets out, I discovered that they actually do not work with the shorter file names.

it appears that [the `.sublime-snippet` extension is *required*](http://sublimetext.info/docs/en/extensibility/snippets.html#snippets-file-format).

As for the tabs vs spaces thing... I wonder if most people will have `translate_tabs_to_spaces` set, and if they don't maybe this will cause more hurt than help? It *is* what sublime recommends, so my inclination is to follow that unless people struggle with it, but might be good to have some others weigh in on it.

**Comment by zachlysobey** [comment]
@MAustinMMDP what do you think the best way to help with this is, as I'm noticing some more small things. Should I submit PR's to your fork, give you feedback here, or something else?

I feel bad spamming the issues here since there are like 1000 watchers...

**Comment by MAustinMMDP** [comment]
@zachlysobey Yeah, maybe it would be best to give feedback here so that peeps can chime in and then based off the feedback submit PR's to my fork. Seems easiest that way and it would help me out a lot. We should definitely correct the extension; I don't see anyone having an issue with that. Thanks so much for your help. It feels like we are finally making some progress.

**Comment by zachlysobey** [comment]
Ok, here's one:

In the sublime *directive* snippet:

`${3}` is hooked up to the dependencies for both the *directive function* and its *Controller*, which are 2 different sets of dependencies.

IMO, the Controller dependencies should be `${4}` (and the other tab-locations incremented of course)

from: https://github.com/MAustinMMDP/angular-styleguide/commit/09b2325d9840c51443f213ca870e7d8a96322e89

I'll submit a PR (to your fork) for the file-names tonight. I can do one for this fix too if we think its good.

**Comment by MAustinMMDP** [comment]
@zachlysobey The extension name change was really quick so I went ahead and took care of it. 

For the sublime directive snippet do you agree we should match Style Y075 and replace the dependencies, which I agree should not be there, with $scope?

**Comment by MAustinMMDP** [comment]
@zachlysobey In regards to the tabs vs spaces thing. I'm not sure if it matters either way as I've found the snippets work with either spaces or tabs. Maybe we let this go until someone submits an issue for it as it is easy to fix?

**Comment by zachlysobey** [comment]
@MAustinMMDP I'm ok with that, but I was alerted to this b/c a friend was doing a 'tab' indented project with these snippets and ended up with a tab/space mixed abomination! Not sure what his settings were though.

**Comment by zachlysobey** [comment]
Not sure if this exists, but I think it would be nice to have a single place where we put snippet prototypes in plain JS to validate these snippets against. I'm noticing some *minor* inconsistencies, and it would be easier to talk about what the *right* format is if we had a such a document.

If that is in place, it would be much easier to say whether or not a snippet conforms to the spec, and the only questions would be tabbing, and completion kinds of things.

**Comment by zachlysobey** [comment]
Another thought I had, and maybe its prohibitively difficult at this point, is that maybe this Sinppet-refactoring project would be easier to merge in if each editor was set up as a different PR? Having to validate that *all* of these changes are solid before merging in will certainly take a significant amount of time still.

**Comment by zachlysobey** [comment]
There's an extra space in the VSCode directive snippet Controller definition:

```
"\tfunction ${Controller}Controller () {",
```

should be

```
"\tfunction ${Controller}Controller() {",
```

**Comment by zachlysobey** [comment]
VSCode snippets should probably also end with a newline.

**Comment by MAustinMMDP** [comment]
@zachlysobey I agree with all the points you have made so for now I am going to close this PR and we can work on my fork. It has become kind of a beast ;). 

You may be right about the VSCode but I have not worked on those yet and they are not included in the PR.

**Comment by ackzell** [comment]
Thanks for the updates!

I am having trouble finding the folder for the templates using an IntelliJ IDEA 15 on Yosemite.

I've looked into ```~/Library/Preferences/IntelliJIdea15```
I also went ahead and created the folder myself, but to no avail.

Could anyone tell me where to find it?

**Comment by MAustinMMDP** [comment]
This should help ... https://www.jetbrains.com/help/idea/15.0/tuning-intellij-idea.html?origin=old_help

**Comment by ackzell** [comment]
Thank you very much @MAustinMMDP, somehow the file I was trying to load wasn't recognized as an XML, recreated it using a text editor and saved it to that location and it worked.

**Comment by MAustinMMDP** [comment]
Your very welcome. Glad I could help :)

**Pull request closed without merging**
