### PR TITLE
Sublime snippets - Initializing $inject too

### PR DESCRIPTION
**Pull request by wmalgoire**
Initializing $inject property with regular expressions in the following snippets :
- ngController
- ngDirective
- ngFactory
- ngService

ngsublimesnippetsdemo

### CODE REVIEW

**Comment by johnpapa** [comment]
cool

**Comment by wmalgoire** [comment]
Thanks !

**Comment by websirnik** [comment]
Why do we need explicit `$inject` declaration? Isn't [ng-annotate](https://github.com/olov/ng-annotate) suppose to do it for us ?

**Comment by intellix** [comment]
My thought exactly, the injection typically happens automatically from another tool, otherwise you'll have a few WTF when you don't change in both places.

**Comment by voor** [comment]
ng-annotate is pretty new to the scene, a lot of this stuff was probably started back when inject had to be explicitly declared.

**Comment by wmgh** [comment]
It's probably a bad idea to use $inject and ng-annotate at the same time, although the author doesn't seem to be afraid by [that](http://stackoverflow.com/a/26692309), Anyway, my intent was to give a choice in the snippets, nothing more :-)

**Comment by wmalgoire** [comment]
It's probably a bad idea to use $inject and ng-annotate at the same time, although the author doesn't seem to be afraid by [that](http://stackoverflow.com/a/26692309), Anyway, my intent was to give a choice in the snippets, nothing more :-)

**Pull request merged**
