### PR TITLE
i18n tr_TR

### PR DESCRIPTION
**Pull request by kel-sakal-biyik**
Turkish translation of the guideline

### CODE REVIEW

**Comment by johnpapa** [comment]
thanks, please add the links to the translations page and the credits (see others for examples)

**Comment by kel-sakal-biyik** [comment]
Hey,
Thank you for preparing such a great guide. I have added the link and credit.

**Comment by johnpapa** [comment]
this cant be merged. can you fix it?

**Comment by kel-sakal-biyik** [comment]
Updated i18n/README.md with your master. I think this can be merged.

**Comment by johnpapa** [comment]
it has a merge conflict. it must be resolved first

**Comment by johnpapa** [comment]
ping :)

**Comment by kel-sakal-biyik** [comment]
Request timed out :)

I will fix this. Sorry for the delay.

**Comment by kel-sakal-biyik** [comment]
I had a lot of issues while trying to solve the merge conflicts. So , I created a new branch and am going to make a new pull request on that branch. I am closing this request.

**Pull request closed without merging**
