### PR TITLE
Remove some deprecated JSHint rules [Fixes #592]

### LINKED ISSUE #592: JSCS `maximumLineLength` vs Jshint `maxlen`
```
"maximumLineLength": {
      "value": 100,
    },
```

vs 

```
"maxlen": 120,
```

this seems to cause a discrepancy.  I am not well versed enough in these two frameworks but in my fork of this styleguide i consolidated the two of them.  I got jshint working in grunt saw the errors, fixed them, then got jscs running but noticed the same lines failing.

### PR DESCRIPTION
**Pull request by zachlysobey**
If/when I get a chance, I'll tack on fixes/replacements for the other deprecated JSHint rules listed in issue #592.

### CODE REVIEW

**Comment by zachlysobey** [comment]
OK, I think that's all I got for this PR.

I think the following 4 JSHint rules are the only deprecated ones left, and their removal doesn't seem quite as straight-forward as the above rules. Perhaps a better topic for a new issue.

 - [**es3**](http://jshint.com/docs/options/#es3) (related JSHint rule: [esversion](http://jshint.com/docs/options/#esversion))
 - [**esnext**](http://jshint.com/docs/options/#esnext) (related JSHint rule: [esversion](http://jshint.com/docs/options/#esversion))
 - [**laxbreak**](http://jshint.com/docs/options/#laxbreak) (related JSCS rule: [requireOperatorBeforeLineBreak](http://jscs.info/rule/requireOperatorBeforeLineBreak))
 - [**laxcomma**](http://jshint.com/docs/options/#laxcomma) (related JSCS rule: [disallowCommaBeforeLineBreak](http://jscs.info/rule/disallowCommaBeforeLineBreak))

**Comment by mattgrande** [comment]
Thanks for tackling this, @zachlysobey!

**Comment by johnpapa** [comment]
thanks, sorry but we have new merge conflicts due to the a1 a2 shuffle. please reopen this when you have a clean PR

thanks!

**Comment by zachlysobey** [comment]
Sry guys, not much of an angular-person nowadays, so unlikely I'll ever get to putting this together again

**Pull request closed without merging**
