### PR TITLE
Refresh french translation

### PR DESCRIPTION
**Pull request by xavhan**
Work in progress : fixing the typos and some awkwardness in french.

### CODE REVIEW

**Comment by johnpapa** [comment]
please do not remove who translated it.

*Translated by [Eric Lemerdy](https://github.com/ericlemerdy)*

**Comment by xavhan** [comment]
@johnpapa yep but i thought placing it at the end of the file would be a better option. Because it messed up with the line numbers and the english and the french versions line numbers did not matched.

**Comment by xavhan** [comment]
I'll finish the rest tomorrow morning, and will maintain it in the future.

**Comment by johnpapa** [comment]
ok. please add your name and his to the top as credits. I like to give the translations credit up high so folks see it.

**Comment by xavhan** [comment]
Allright, it is finished ! 

I took the liberty to italicize (between *) some english words that do not make sense in being translated (such as factory, scope…).

poke @ericlemerdy for reviewing the changes

@johnpapa : I re-added translators as you asked me but I still think it it a bad idea to unmatch lines between original content and the translations files. It make it more difficult for translators to find changes. 

I'll submit a new PR with an acceptable solution i found.

**Comment by xavhan** [comment]
@ericlemerdy PR submitted

**Pull request merged**
