### PR TITLE
Angular Style Guide - PDF 

### PR DESCRIPTION
**Pull request by tejzpr**
Angular Style Guide in PDF format for offline reading.

### CODE REVIEW

**Comment by brutalcrozt** [comment]
consider using converter? new commit will not reflect the changes in pdf isn't?

**Comment by tejzpr** [comment]
New commits needs to be converted to PDF, I can update one a week.

**Comment by johnpapa** [comment]
thanks, but i dont think hosting a PDF up here is ideal. Folks can create one as needed.

**Comment by zachlysobey** [comment]
This could easily exist as a separate app that pulls in the style-guide using Git, and generates a pdf.

Would be a cool project perhaps.

**Comment by zachlysobey** [comment]
Also note that you don't need to go this far for offline reading. Just pull down the repo. You could use a markdown viewer for nicer display than raw markdown.

**Comment by johnpapa** [comment]
I want to thank you for making this PR. I realize you took the time to think this through and make the request.

**Comment by tejzpr** [comment]
I like this guide and thought of reading it during long transit times in bus, I couldn't find a better option than a generating a PDF file and loading it up on my smartphone.

**Pull request closed without merging**
